name: Build and Release

on:
  push:
    branches: [ main ]
  create:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Build
      run: make dist
    
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/*.tar.gz

  release:
    needs: [build]
    if: ${{ startsWith(github.ref,'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Display structure of downloaded files
        run: ls -R
      - name: Create release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "none"
          ALLOW_EMPTY_CHANGELOG: "true"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: |
            *.tar.gz
